(() => {
const REPO='Nkumarbaghel/cgneelbaghel', PATH='posts.js', BRANCH='main', OWNER='Nkumarbaghel', GALLERY_DIR='images/gallery';
const $=id=>document.getElementById(id); let token='', posts=[], editingIndex=-1, fileSha='', idleTimer=null, lastActivity=Date.now();
const SESSION_MS=30*60*1000, MAX_IMAGE_BYTES=8*1024*1024;
function today(){return new Date().toISOString().slice(0,10)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function slug(t){return t.toLowerCase().trim().replace(/[^a-z0-9\u0900-\u097f\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').slice(0,60)||'new-post'}
function htmlToText(h){const d=document.createElement('div');d.innerHTML=h||'';return d.innerText.replace(/\n{3,}/g,'\n\n').trim()}
function textToHtml(t){return t.split(/\n\s*\n/).filter(Boolean).map(x=>`<p>${esc(x).replace(/\n/g,'<br>')}</p>`).join('\n')}
function collect(){const title=$('title').value.trim();return{id:$('postId').value.trim()||slug(title),title,date:$('date').value||today(),category:$('category').value.trim(),image:$('image').value.trim(),excerpt:$('excerpt').value.trim(),content:textToHtml($('content').value.trim())}}
function status(msg,ok=false){$('status').textContent=msg;$('status').className='status '+(ok?'ok':'err')}
function loginStatus(msg,ok=false){$('loginStatus').textContent=msg;$('loginStatus').className='status '+(ok?'ok':'err')}
function galleryStatus(msg,ok=false){$('galleryStatus').textContent=msg;$('galleryStatus').className='status '+(ok?'ok':'err')}
function renderList(){const q=$('listSearch').value.toLowerCase();const f=posts.map((p,i)=>({p,i})).filter(x=>(x.p.title+' '+(x.p.category||'')).toLowerCase().includes(q));$('postList').innerHTML=f.length?f.map(x=>`<div class="post-item ${x.i===editingIndex?'active':''}" data-i="${x.i}"><strong>${esc(x.p.title)}</strong><span>${esc(x.p.category||'')} • ${esc(x.p.date||'')}</span></div>`).join(''):'<div class="small">कोई लेख नहीं मिला</div>';$('postList').querySelectorAll('.post-item').forEach(e=>e.onclick=()=>loadPost(+e.dataset.i))}
function clearForm(){editingIndex=-1;$('formTitle').textContent='नया लेख';$('postForm').reset();$('date').value=today();$('postId').value='';$('preview').classList.add('hidden');$('deleteBtn').disabled=true;renderList()}
function loadPost(i){const p=posts[i];editingIndex=i;$('formTitle').textContent='लेख संपादित करें';$('postId').value=p.id||'';$('title').value=p.title||'';$('category').value=p.category||'';$('date').value=p.date||today();$('image').value=p.image||'';$('excerpt').value=p.excerpt||'';$('content').value=htmlToText(p.content||'');$('deleteBtn').disabled=false;$('preview').classList.add('hidden');renderList();window.scrollTo({top:0,behavior:'smooth'})}
async function gh(path,opts={}){const r=await fetch('https://api.github.com/repos/'+REPO+'/contents/'+path+'?ref='+BRANCH,{...opts,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28',...(opts.headers||{})}});const data=await r.json();if(!r.ok)throw new Error(data.message||('GitHub error '+r.status));return data}
async function verifyOwnerAndRepo(){const meR=await fetch('https://api.github.com/user',{headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}});const me=await meR.json();if(!meR.ok)throw new Error('Token invalid है या GitHub ने access अस्वीकार किया।');if(String(me.login||'').toLowerCase()!==OWNER.toLowerCase())throw new Error('⛔ यह GitHub account Admin नहीं है। केवल '+OWNER+' account को अनुमति है।');const repoR=await fetch('https://api.github.com/repos/'+REPO,{headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}});const repo=await repoR.json();if(!repoR.ok)throw new Error('Repository access नहीं मिला।');if(repo.permissions&&repo.permissions.push!==true)throw new Error('⛔ इस token में repository Contents write permission नहीं है।');return me}
async function connect(){token=$('token').value.trim();if(!token){loginStatus('Token डालें।');return}$('loginBtn').disabled=true;loginStatus('GitHub account और repository permission verify हो रही है...',true);try{const me=await verifyOwnerAndRepo();await loadPosts();$('sessionUser').textContent='👤 '+me.login;$('loginPanel').classList.add('hidden');$('app').classList.remove('hidden');clearForm();startSession()}catch(e){token='';loginStatus(e.message)}finally{$('loginBtn').disabled=false}}
async function loadPosts(){const d=await gh(PATH);fileSha=d.sha;const raw=decodeURIComponent(escape(atob(d.content.replace(/\n/g,''))));const fn=new Function(raw+'\nreturn window.posts;');const old=window.posts;window.posts=undefined;const result=fn();window.posts=old;posts=Array.isArray(result)?result.map(p=>({...p})):[];renderList()}
function generateJS(){return 'window.posts = '+JSON.stringify(posts,null,2)+';\n'}
function b64(s){return btoa(unescape(encodeURIComponent(s)))}
function fileToBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)})}
function safeFilePart(s){return String(s||'photo').toLowerCase().trim().replace(/[^a-z0-9-_]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,50)||'photo'}
async function uploadGallery(){touch();const input=$('galleryFile'),file=input.files&&input.files[0];if(!file){galleryStatus('पहले कोई photo चुनें।');return}if(!/^image\/(jpeg|png|webp|gif)$/.test(file.type)){galleryStatus('❌ केवल JPG, PNG, WEBP या GIF photo upload करें।');return}if(file.size>MAX_IMAGE_BYTES){galleryStatus('❌ Photo 8 MB से बड़ी है।');return}const caption=safeFilePart($('galleryCaption').value)||safeFilePart(file.name.replace(/\.[^.]+$/,''));const ext=(file.name.match(/\.(jpe?g|png|webp|gif)$/i)||['','.jpg'])[1].toLowerCase().replace('jpeg','jpg');const filename=`${Date.now()}-${caption}.${ext}`;const path=GALLERY_DIR+'/'+filename;$('uploadGalleryBtn').disabled=true;$('uploadProgress').style.width='10%';galleryStatus('Photo तैयार की जा रही है...',true);try{const content=await fileToBase64(file);$('uploadProgress').style.width='45%';const d=await gh(path,{method:'PUT',body:JSON.stringify({message:'Add gallery photo: '+filename,content,branch:BRANCH})});$('uploadProgress').style.width='100%';galleryStatus('✅ Photo Gallery में upload हो गई! अब public Gallery में दिखाई देगी।',true);input.value='';$('galleryCaption').value='';setTimeout(()=>{$('uploadProgress').style.width='0%'},900);return d}catch(e){$('uploadProgress').style.width='0%';galleryStatus('❌ Upload failed: '+e.message)}finally{$('uploadGalleryBtn').disabled=false}}
async function publish(){touch();const p=collect();if(!p.title||!p.category||!p.content){status('शीर्षक, category और लेख जरूरी है।');return}if(editingIndex>=0)posts[editingIndex]=p;else posts.unshift(p);$('publishBtn').disabled=true;status('GitHub पर publish हो रहा है...',true);try{const d=await gh(PATH,{method:'PUT',body:JSON.stringify({message:(editingIndex>=0?'Update blog: ':'Publish blog: ')+p.title,content:b64(generateJS()),sha:fileSha,branch:BRANCH})});fileSha=d.content.sha;renderList();status('✅ Publish सफल! GitHub Pages थोड़ी देर में नया लेख दिखाएगा।',true)}catch(e){status('❌ Publish failed: '+e.message)}finally{$('publishBtn').disabled=false}}
async function del(){touch();if(editingIndex<0)return;if(!confirm('क्या यह लेख delete करना है?'))return;const title=posts[editingIndex].title;posts.splice(editingIndex,1);$('deleteBtn').disabled=true;try{const d=await gh(PATH,{method:'PUT',body:JSON.stringify({message:'Delete blog: '+title,content:b64(generateJS()),sha:fileSha,branch:BRANCH})});fileSha=d.content.sha;clearForm();status('✅ लेख delete हो गया और GitHub update हो गया।',true)}catch(e){status('❌ Delete failed: '+e.message);await loadPosts()}}
function preview(){touch();const p=collect();$('preview').innerHTML=`<h2>${esc(p.title)}</h2><p class="small">${esc(p.category)} • ${esc(p.date)}</p>${p.image?`<img src="${esc(p.image)}" alt="">`:''}<p><b>${esc(p.excerpt)}</b></p><div>${p.content}</div>`;$('preview').classList.remove('hidden')}
function logout(){token='';posts=[];fileSha='';editingIndex=-1;stopSession();$('app').classList.add('hidden');$('loginPanel').classList.remove('hidden');$('token').value='';$('sessionUser').textContent='';loginStatus('आप logout हो चुके हैं।',true);window.scrollTo({top:0,behavior:'smooth'})}
function touch(){lastActivity=Date.now()}
function startSession(){touch();stopSession();idleTimer=setInterval(()=>{if(Date.now()-lastActivity>SESSION_MS){logout();loginStatus('⏱️ सुरक्षा के लिए 30 मिनट inactivity के बाद logout किया गया।')}},60000)}
function stopSession(){if(idleTimer){clearInterval(idleTimer);idleTimer=null}}
['click','keydown','input','scroll','touchstart'].forEach(ev=>document.addEventListener(ev,touch,{passive:true}));
$('loginBtn').onclick=connect;$('token').addEventListener('keydown',e=>{if(e.key==='Enter')connect()};$('logoutBtn').onclick=logout;$('postForm').onsubmit=e=>{e.preventDefault();touch();const p=collect();if(editingIndex>=0)posts[editingIndex]=p;else posts.unshift(p);renderList();status('लेख editor में सेव है। Publish दबाकर GitHub पर भेजें।',true)};$('publishBtn').onclick=publish;$('deleteBtn').onclick=del;$('previewBtn').onclick=preview;$('newBtn').onclick=clearForm;$('clearBtn').onclick=clearForm;$('listSearch').oninput=renderList;$('uploadGalleryBtn').onclick=uploadGallery;$('date').value=today();$('deleteBtn').disabled=true;
})();
