// Blog category folders: articles stay hidden until a folder is tapped.
document.addEventListener("DOMContentLoaded",()=>{
  const hero=document.querySelector(".blog-hero");
  if(!hero||typeof posts==="undefined"||document.querySelector("#categoryFolders"))return;
  const categories=[["💻","Digital / Technology","Digital, मोबाइल, इंटरनेट और तकनीक","digital"],["📰","News / समाचार","खबरें और समाचार विश्लेषण","news"],["👨‍💻","Career / Jobs","नौकरी, Resume और Career","career"],["🌾","छत्तीसगढ़ | संस्कृति और त्योहार","छत्तीसगढ़ के तीज-त्योहार और संस्कृति","chhattisgarh"],["📚","Education / शिक्षा","पढ़ाई और ज्ञान","education"],["💼","Business / Finance","बिजनेस और वित्त","business"],["🤖","AI / Artificial Intelligence","AI और ChatGPT","ai"],["🌐","Internet / Social Media","वेबसाइट और सोशल मीडिया","internet"],["🎭","Culture / संस्कृति","कला, लोकजीवन और संस्कृति","culture"],["📝","मेरे विचार","विशेष लेख और व्यक्तिगत विचार","thoughts"]];
  const norm=v=>String(v||"").toLowerCase();
  const classify=(p,key)=>{const t=norm(`${p.title||""} ${p.category||""} ${p.excerpt||""}`);if(key==="chhattisgarh")return /छत्तीसगढ़|chhattisgarh/.test(t)&&!/डिजिटल बदलाव|digital/.test(t);if(key==="digital")return /डिजिटल|digital|technology|तकनीक/.test(t)&&!/छत्तीसगढ़/.test(t);if(key==="news")return /news|समाचार|खबर/.test(t);if(key==="career")return /career|job|jobs|नौकरी|resume|रिज्यूमे/.test(t);if(key==="education")return /education|शिक्षा|पढ़ाई|परीक्षा/.test(t);if(key==="business")return /business|finance|बिजनेस|व्यापार|वित्त/.test(t);if(key==="ai")return /\bai\b|artificial intelligence|chatgpt|एआई/.test(t);if(key==="internet")return /internet|इंटरनेट|social media|सोशल मीडिया|facebook|instagram|youtube/.test(t);if(key==="culture")return /culture|संस्कृति|लोककला|लोकजीवन/.test(t);if(key==="thoughts")return /विचार|thought/.test(t);return false};
  const esc=s=>String(s||"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
  const date=s=>{const d=new Date((s||"")+"T00:00:00");return isNaN(d)?"":d.toLocaleDateString("hi-IN",{day:"numeric",month:"long",year:"numeric"})};
  const hideOutsideCards=()=>{const p=document.querySelector("#posts"),t=document.querySelector(".blog-tools");if(p)p.style.setProperty("display","none","important");if(t)t.style.setProperty("display","none","important");};
  hideOutsideCards();
  const observer=new MutationObserver(hideOutsideCards);if(document.body)observer.observe(document.body,{childList:true,subtree:true});
  const section=document.createElement("section");section.id="categoryFolders";section.className="category-folders";
  section.innerHTML=`<div class="category-folders-head"><span>📂 BLOG CATEGORIES</span><h2>जिस विषय में रुचि हो, वही चुनें</h2><p>फोल्डर पर टैप करें — उसी विषय के ब्लॉग यहीं खुलेंगे।</p></div><div class="category-folder-grid">${categories.map(([i,n,d,k])=>`<button type="button" class="category-folder" data-key="${k}"><span class="folder-icon">${i}</span><strong>${n}</strong><small>${d}</small><span class="folder-open">फोल्डर खोलें →</span></button>`).join("")}</div>`;
  hero.insertAdjacentElement("afterend",section);
  function openFolder(key,name){const unique=new Map();posts.filter(p=>classify(p,key)).forEach(p=>unique.set(`${norm(p.title)}|${p.date||""}`,p));const matches=Array.from(unique.values()).sort((a,b)=>String(b.date).localeCompare(String(a.date)));const modal=document.createElement("div");modal.className="folder-modal";modal.innerHTML=`<div class="folder-modal-box"><div class="folder-modal-head"><h3>📂 ${esc(name)} <span style="color:#999;font-size:13px;font-weight:400">(${matches.length} लेख)</span></h3><button class="folder-close" type="button">✕</button></div><div class="folder-posts">${matches.length?matches.map(p=>`<article class="folder-post"><small>${esc(p.category||"सामान्य")} • ${date(p.date)}</small><h4>${esc(p.title)}</h4><p>${esc(p.excerpt||"")}</p><a href="blog.html?post=${encodeURIComponent(p.id)}">पूरा लेख पढ़ें →</a></article>`).join(""):`<p style="color:#aaa">इस फोल्डर में अभी कोई लेख उपलब्ध नहीं है।</p>`}</div></div>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector(".folder-close").onclick=close;modal.onclick=e=>{if(e.target===modal)close()};}
  section.querySelectorAll(".category-folder").forEach(b=>b.onclick=()=>{const x=categories.find(a=>a[3]===b.dataset.key);if(x)openFolder(x[3],x[1])});
});
